### PR TITLE
Fix Raspberry tasks for Debian

### PR DESCRIPTION
**Pull request by kcirrr**
Debian Buster was previously recognized as Raspbian, and there were no tasks for Debian Bullseye.
This pull requests changes the os detection tasks and adds tasks for Debian to make sure the behaviour for the previous Debian versions stays the same. It also adds Debian 11 specific tasks.

### CODE REVIEW

**Comment by cyc1ingsir** [comment]
I tested this on a fresh Installation of Raspi-OS arm64 lite image (https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-11-08/) and had to make two changes:
Inside Debian-11.yml `cmdlin.txt` is still at `path: /boot/cmdline.txt` and not `path: /boot/firmware/cmdline.txt`

Since `iptables` was not installed I added the below task to Debian-11.yml

```yaml
- name: Install iptables
  apt:
    name: iptables
```

There is an additional error I still need to debug:
```
# systemctl status k3s.service
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2021-11-09 19:47:03 CET; 1s ago
       Docs: https://k3s.io
    Process: 5396 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 5397 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 5398 ExecStart=/usr/local/bin/k3s server --data-dir /var/lib/rancher/k3s --disable servicelb (code=exited, status=1/FAILURE)
   Main PID: 5398 (code=exited, status=1/FAILURE)

# journalctl -xe
....
level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
level=info msg="Run: k3s kubectl"
level=fatal msg="failed to find memory cgroup (v2)"

```

**Comment by kcirrr** [comment]
Thanks for testing this!

I didn't know the bullseye arm64 Raspi-OS lite image identifies as regular Debian 11.
The install iptables task is fine for both of course (might also be required for the regular Debian 11).

But the different paths for `cmdline.txt` makes things a bit difficult.
Debian 11: `/boot/firmware/cmdline.txt`
Raspi-OS lite: `/boot/cmdline.txt`

Not sure if we could find a different way to detect the OS, to make sure Raspi-OS lite is properly detected.
But it's also possible to use a `stat` task to check for the `cmdline.txt` paths.

I'll try to make something and test it on a fresh install of Raspi-OS lite and Debian 11.

**Comment by manzato** [comment]
FWIW I ran this PR (with the changes mentioned by @cyc1ingsir ) over 3 Rpi4 (freshly installed with 2021-10-30-raspios-bullseye-arm64-lite) and it worked perfectly.

**Comment by kcirrr** [comment]
I checked both the amd64 RaspiOS Lite and regular Debian 11.
They both have the exact same lsb release info:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

I added the iptables install task.
And i added a task to check if /boot/firmware/cmdline.txt exists.
And i made the path for the cmdline.txt lineinfile task a ternary.
This made the Debian11.yml file obsolete.

I've tested this, it works both on amd64 RaspiOS Lite and regular Debian 11.

**Comment by jason-edstrom** [comment]
Tested these fixes across 6 Rpi 4Bs.  Flawless.  Kudos, @kcirrr!

**Comment by sebastiangaiser** [comment]
Works for me too. 
Awesome work 👍🏻

**Comment by Dowster64** [comment]
As mentioned in PR#185 (not sure how to link) husjon noted that Raspberry Pi OS Lite (64-bit) comes with nf_tables (so iptables cmd works - mine reports iptables v1.8.7 (nf_tables).

**Review by dereknola — APPROVED** [review]

**Pull request merged**
