### PR TITLE
Set firewall rules for custom CIDR ranges

### PR DESCRIPTION
**Pull request by laszlojau**
#### Changes ####

role: prereq

#### Linked Issues ####

#292

### CODE REVIEW

**Comment by laszlojau** [comment]
I tried to keep multiple options open for passing the CIDR range to the prereq role, happy to update/simplify the logic if needed.

**Comment by dereknola** [comment]
I'm happy to support different options. But you should simplify the logic. Just have a `cluster_cidr` and `service_cidr` default vars that could be overriden by the inventory var. 

Additionally, you need to sign all your commits to comply with the DCO.

**Comment by dereknola** [comment]
Yeah i think that would work:
- If hard defined as a variable, use that.
- Otherwise attempt to figure it out from the k3s config.yaml values 
- Otherwise use the defaults

**Comment by laszlojau** [comment]
Updated the logic and signed the commit, let me know if you need anything else.

**Review by dereknola — APPROVED** [review]

**Pull request merged**
