### PR TITLE
Finished k3s-ha implementation; Add three (3) cluster VIP methods implemented via ansible

### PR DESCRIPTION
**Pull request by jon-stumpf**
I have finished the **k3s-ha** implementation so that it implements the HA embedded database using _etcd_ whenever three (3) or more servers are defined in _hosts.ini_.  I have also implemented three methods to manage cluster VIPs in front of the control-plane:

1. external
2. kube-vip
3. keepalived

This branch addresses:

- #32
- #97
- #123
- #127
- #131

I consider this branch stable although I have more to do (see TODO.md).

This work builds on my previous PRs: #158 and #164.

### CODE REVIEW

**Comment by jon-stumpf** [comment]
@geerlingguy,

I would be interested in your critique of this work.  Also, any suggestions for improvement.
Thanks.

\- jss

**Comment by h0tw1r3** [comment]
working as intended. thank you for sharing your work!

**Comment by dereknola** [comment]
Closing this. I appreciate you dedication to keeping this repo updated in your own fork @jon-stumpf. With the newest changes, this PR is heavily offset and will need a major overhaul. Also, going forward, this repo will not be implementing any VIP by default. With the `api_endpoint` variable, users can easily setup a VIP themselves and then connect into afterwards.

**Comment by jon-stumpf** [comment]
> Closing this. I appreciate you dedication to keeping this repo updated in your own fork @jon-stumpf. With the newest changes, this PR is heavily offset and will need a major overhaul. Also, going forward, this repo will not be implementing any VIP by default. With the `api_endpoint` variable, users can easily setup a VIP themselves and then connect into afterwards. 

@dereknola You are the first committer to respond to my work from over two years ago.  Are there capabilities that I implemented that are still not completed that an overhaul would be beneficial?  And, if so, will someone respond to my pull request in a timely fashion?

**Comment by dereknola** [comment]
I will take a look tomorrow at all the features built into your fork of this project. Any capabilities that would be beneficial I will open issues about. You can feel free to submit PRs for those features or not, your choice. Going forward, any PRs you submit I will attempt to answer within a few days. My main job is still K3s development but I should have time to maintain this repo (i.e. deal with new issues and PRs) just don't expect alot direct feature work from me after this week.

**Comment by jon-stumpf** [comment]
I am working on bringing my repo in-line with upstream.  I am performing all my work on the [rebase-upstream](https://github.com/jon-stumpf/k3s-ansible/tree/rebase-upstream) branch in my repo.  As I get close, I will then look at producing PRs for your master.

**Pull request closed without merging**
